server:
  port: 9000

spring:
  application:
    name: mycgv

  logging:
    level:
      root: DEBUG

  datasource:
    url: jdbc:mysql://3.36.151.60:3306/CGV?useUnicode=true&characterEncoding=UTF-8 # ??????
    username: paper # ??????
    password: 1234 # ??????
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8??

  jpa:
    properties:
      hibernate:
        connection:
          isolation: 2

  sql:
    init:
      platform: mysql

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB


  file:
    dir: C:/upload/

